version: "3.8"
services:
  postgres:
    container_name: supabot-ai-db
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sbdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
